version: '3'
services:
  web:
    build: .
    image: mycourseapi_compose
    container_name: mycourseapi_1
    depends_on:
      - db
    ports:
     - "9999:8080"
    volumes:
     - /c/Users/HQZ/Documents/workspace-sts-3.9.4.RELEASE/course-api-data/logs:/export/netsite/ext-admin/logs/
  db:
    image: "mysql:latest"
    container_name: dockertoolbox_databases_1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password